/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiSearchRouteImport } from './routes/api/search'
import { Route as ApiSearchIdRouteImport } from './routes/api/search.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSearchRoute = ApiSearchRouteImport.update({
  id: '/api/search',
  path: '/api/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSearchIdRoute = ApiSearchIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiSearchRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/search': typeof ApiSearchRouteWithChildren
  '/api/search/$id': typeof ApiSearchIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/search': typeof ApiSearchRouteWithChildren
  '/api/search/$id': typeof ApiSearchIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/search': typeof ApiSearchRouteWithChildren
  '/api/search/$id': typeof ApiSearchIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/search' | '/api/search/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/search' | '/api/search/$id'
  id: '__root__' | '/' | '/api/search' | '/api/search/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiSearchRoute: typeof ApiSearchRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/search': {
      id: '/api/search'
      path: '/api/search'
      fullPath: '/api/search'
      preLoaderRoute: typeof ApiSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/search/$id': {
      id: '/api/search/$id'
      path: '/$id'
      fullPath: '/api/search/$id'
      preLoaderRoute: typeof ApiSearchIdRouteImport
      parentRoute: typeof ApiSearchRoute
    }
  }
}

interface ApiSearchRouteChildren {
  ApiSearchIdRoute: typeof ApiSearchIdRoute
}

const ApiSearchRouteChildren: ApiSearchRouteChildren = {
  ApiSearchIdRoute: ApiSearchIdRoute,
}

const ApiSearchRouteWithChildren = ApiSearchRoute._addFileChildren(
  ApiSearchRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiSearchRoute: ApiSearchRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
